name: 🏗 Build the Test

on:
    workflow_dispatch:

permissions: write-all

concurrency:
    group: pages
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            base_url: ${{ steps.pages.outputs.base_url }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with: 
                    submodules: recursive
                    fetch-depth: 0
            -   name: Pull Repo
                run: git pull
            -   name: Get Haxe
                run: |
                  sudo add-apt-repository ppa:haxe/releases -y
                  sudo apt-get update
                  sudo apt-get install haxe -y --quiet
                  mkdir ~/haxelib && haxelib setup ~/haxelib
            -   name: Install OpenFL
                run: haxelib install openfl --quiet
            -   name: Install Lime
                run: haxelib install lime --quiet
            -   name: Setup Lime
                run: haxelib run lime setup -y
            -   name: build project
                run: lime build html5 -clean -final
            -   name: Setup Pages
                id: pages
                uses: actions/configure-pages@v3
            -   name: Upload Artifact
                uses: actions/upload-pages-artifact@v2
                with: 
                    path: ./export/html5/bin
    deploy:
        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        outputs:
            base_url: ${{ needs.build.outputs.base_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Deploy
                id: deployment
                uses: actions/deploy-pages@v2

